import { Hono } from "hono";
import { HTTPException } from "hono/http-exception";
import { logger } from "hono/logger";
import { cache } from "hono/cache";
import { cors } from "hono/cors";

const app = new Hono();
app.use(logger());

// Enable CORS for frontend
app.use('*', cors({
  origin: (origin) => {
    if (origin === 'http://localhost:3000' || origin === 'https://geo.sleepstars.de') {
      return origin;
    }

    try {
      const url = new URL(origin);
      const isPagesDeployment =
        url.protocol === 'https:' &&
        url.hostname.endsWith('.pages.dev');
      return isPagesDeployment ? origin : undefined;
    } catch {
      return undefined;
    }
  },
  allowMethods: ['GET', 'POST', 'OPTIONS'],
  allowHeaders: ['Content-Type'],
}));

// Cache GET responses when running on Cloudflare. The VPS build delegates this
// responsibility to nginx, where the Cache API does not exist.
if (typeof caches !== "undefined") {
  app.get(
    "*",
    cache({
      cacheName: "rulelist",
      cacheControl: "max-age=1800",
    })
  );
}

// Try to fetch prebuilt JSON rules (generated by CI) only
type RuleItem = { type: "domain" | "full" | "regexp"; value: string; attrs?: string[] };
type RuleJSON = { name: string; rules: RuleItem[] };

type GeoIPJSON = { name: string; cidr4?: string[]; cidr6?: string[] };

type CacheEntry<T> = { data: T; expires: number };

const GEOSITE_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes
const GEOIP_CACHE_TTL_MS = 5 * 60 * 1000;

const geositeCache = new Map<string, CacheEntry<RuleJSON>>();
const geoipCache = new Map<string, CacheEntry<GeoIPJSON>>();
const SEARCH_KV_TTL_SECONDS = 3 * 24 * 60 * 60; // 3 days
const SEARCH_SOFT_TTL_SECONDS = 6 * 60 * 60; // 6 hours (soft TTL)

const schedule = (c: any, promise: Promise<unknown>) => {
  try {
    const ec: any = (c as any).executionCtx;
    if (ec && typeof ec.waitUntil === "function") {
      ec.waitUntil(promise);
    }
  } catch (_) {
    // Ignore if execution context not available
  }
};

const cleanupCache = <T>(cacheMap: Map<string, CacheEntry<T>>, now: number): void => {
  for (const [k, entry] of cacheMap) {
    if (entry.expires <= now) cacheMap.delete(k);
  }
};

const ensureDb = (env: EnvBindings): D1Database => {
  const db = env.DB;
  if (!db) {
    throw new HTTPException(500, { message: "D1 database not configured" });
  }
  return db;
};

const parseAttrsJson = (text: string | null | undefined): string[] => {
  if (!text) return [];
  try {
    const arr = JSON.parse(text);
    if (Array.isArray(arr)) {
      return arr
        .map((item) => String(item).trim().toLowerCase())
        .filter((item) => item.length > 0);
    }
  } catch (_) {
    // ignore malformed
  }
  return [];
};

const buildDomainSuffixes = (host: string): string[] => {
  const parts = host.split(".").filter((segment) => segment.length > 0);
  const suffixes: string[] = [];
  for (let i = 0; i < parts.length; i += 1) {
    suffixes.push(parts.slice(i).join("."));
  }
  return suffixes;
};

const escapeLikePattern = (input: string): string => {
  return input.replace(/[\\%_]/g, (m) => `\\${m}`);
};

const chunkArray = <T>(items: T[], size: number): T[][] => {
  if (size <= 0) return [items];
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    chunks.push(items.slice(i, i + size));
  }
  return chunks;
};

const reverseDomainValue = (value: string): string | null => {
  const trimmed = value.trim().replace(/^\*\./, "").replace(/\.+$/, "");
  if (!trimmed) return null;
  const parts = trimmed.split(".").filter((segment) => segment.length > 0);
  if (parts.length === 0) return null;
  return parts.reverse().join(".");
};

let geositeValueRevAvailable: boolean | null = null;
let geositeFtsAvailable: boolean | null = null;
let geoipCidrLowerAvailable: boolean | null = null;

const buildSearchTokens = (query: string): string[] => {
  const set = new Set<string>();
  const trimmed = query.trim();
  const queryLower = trimmed.toLowerCase();
  const hostLower = extractHostCandidate(trimmed).toLowerCase();
  const push = (token: string) => {
    const value = token.trim();
    if (value.length >= 2) set.add(value);
  };
  if (queryLower) push(queryLower);
  if (hostLower) push(hostLower);
  for (const token of queryLower.split(/[^a-z0-9]+/)) push(token);
  for (const token of hostLower.split(/[^a-z0-9]+/)) push(token);
  return Array.from(set);
};

const sanitizeFtsToken = (token: string): string => {
  return token.replace(/[^a-z0-9]/gi, "").toLowerCase();
};

const buildFtsMatchQuery = (tokens: string[]): string | null => {
  const cleaned = tokens
    .map(sanitizeFtsToken)
    .filter((token) => token.length >= 2)
    .map((token) => `${token}*`);
  if (cleaned.length === 0) return null;
  return cleaned.join(" ");
};

const bigIntToHex = (value: bigint): string => {
  return value.toString(16).padStart(32, "0");
};

type EnvBindings = {
  SRS_BUCKET?: R2Bucket;
  GEO_KV?: KVNamespace;
  DB?: D1Database;
  PUBLIC_BASE_URL?: string;
};

const withPublicIndexUrls = (
  type: "geosite" | "geoip",
  index: Record<string, string>,
  env: EnvBindings
): Record<string, string> => {
  const baseUrl = env.PUBLIC_BASE_URL?.trim().replace(/\/+$/, "");
  if (!baseUrl) return index;

  return Object.fromEntries(
    Object.keys(index).map((name) => [name, `${baseUrl}/${type}/${encodeURIComponent(name)}`])
  );
};

const fetchIndexMap = async (
  type: "geosite" | "geoip",
  env: EnvBindings,
  bypassKv = false
): Promise<Record<string, string>> => {
  const kv = bypassKv ? undefined : env.GEO_KV;
  if (kv) {
    try {
      const cached = (await kv.get(`${type}:index`, { type: "json", cacheTtl: 3600 })) as
        | Record<string, string>
        | null;
      if (cached && typeof cached === "object") {
        return withPublicIndexUrls(type, cached, env);
      }
    } catch (_) {
      // ignore KV errors and fallback to R2
    }
  }

  const bucket = env.SRS_BUCKET;
  if (!bucket) {
    throw new HTTPException(500, { message: "SRS bucket not configured" });
  }

  const key = type === "geosite" ? "geosite/index.json" : "geoip/index.json";
  const obj = await bucket.get(key);
  if (!obj) {
    throw new HTTPException(404, { message: "Index not found" });
  }
  try {
    const data = (await (obj as any).json?.()) as Record<string, string> | undefined;
    if (data && typeof data === "object") return withPublicIndexUrls(type, data, env);
  } catch (_) {
    // ignore json() errors; fallback to manual parse
  }
  const ab = await obj.arrayBuffer();
  const text = new TextDecoder().decode(ab);
    return withPublicIndexUrls(type, JSON.parse(text) as Record<string, string>, env);
};

const getJsonRules = async (name: string, r2?: R2Bucket): Promise<RuleJSON | null> => {
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  const now = Date.now();
  cleanupCache(geositeCache, now);
  for (const candidate of candidates) {
    const cached = geositeCache.get(candidate);
    if (cached && cached.expires > now) {
      return cached.data;
    }
  }
  if (r2) {
    for (const n of candidates) {
      const key = `geosite-json/${n}.json`;
      try {
        const obj = await r2.get(key);
        if (!obj) continue;
        let data: RuleJSON | null = null;
        try {
          if (typeof (obj as any).json === "function") {
            const parsed = await (obj as any).json();
            if (parsed && typeof parsed === "object" && Array.isArray((parsed as any).rules)) {
              data = parsed as RuleJSON;
            }
          }
        } catch (_) {
          // ignore json() errors and fall back to manual parse
        }
        if (!data) {
          const ab = await obj.arrayBuffer();
          const text = new TextDecoder().decode(ab);
          data = JSON.parse(text) as RuleJSON;
        }
        if (data && data.name && Array.isArray(data.rules)) {
          const expires = Date.now() + GEOSITE_CACHE_TTL_MS;
          const variants = Array.from(new Set([...candidates, data.name, data.name.toUpperCase(), data.name.toLowerCase()]));
          for (const variant of variants) {
            geositeCache.set(variant, { data, expires });
          }
          return data;
        }
      } catch (_) {
        // keep looping; try next candidate variant
      }
    }
  }
  return null;
};

const genSurgeListFromJson = async (
  data: RuleJSON,
  filter: string | null = null
): Promise<string> => {
  const lines: string[] = [];
  for (const r of data.rules) {
    // filter by attribute
    // Supports @cn and @!cn (negation). Attribute compare is case-insensitive.
    if (filter) {
      const neg = filter.startsWith("!");
      const target = (neg ? filter.slice(1) : filter).toLowerCase();
      const attrs = (r.attrs || []).map((a) => a.toLowerCase());
      const has = attrs.includes(target);
      if ((!neg && !has) || (neg && has)) continue;
    }
    switch (r.type) {
      case "domain":
        lines.push(`DOMAIN-SUFFIX,${r.value}`);
        break;
      case "full":
        lines.push(`DOMAIN,${r.value}`);
        break;
      case "regexp":
        // Skip regex rules to avoid generating overly broad wildcard entries.
        continue;
    }
  }
  return lines.join("\n");
};

// ---- Egern rule-set generators ----
const yamlQuote = (input: string): string => {
  // Use JSON stringifier for simple double-quoted YAML-safe output
  return JSON.stringify(input);
};

const extractSimpleKeywordUnion = (pattern: string): string[] | null => {
  let p = pattern.trim();
  if (!p) return null;
  // strip anchors
  if (p.startsWith("^")) p = p.slice(1);
  if (p.endsWith("$")) p = p.slice(0, -1);
  // strip non-capturing or capturing group wrapper
  if ((p.startsWith("(?:") && p.endsWith(")")) || (p.startsWith("(") && p.endsWith(")"))) {
    p = p.replace(/^\(\?:?/, "").replace(/\)$/, "");
  }
  // allow only word chars, hyphen and '|' separators
  if (!/^[A-Za-z0-9_|-]+$/.test(p)) return null;
  const items = p.split("|").map((s) => s.trim()).filter((s) => s.length > 0);
  if (items.length <= 1) return null;
  const seen = new Set<string>();
  const out: string[] = [];
  for (const it of items) {
    const key = it.toLowerCase();
    if (key.length < 2) continue;
    if (!seen.has(key)) {
      seen.add(key);
      out.push(it);
    }
  }
  return out.length > 0 ? out : null;
};

const genEgernGeositeYamlFromJson = async (
  data: RuleJSON,
  filter: string | null = null
): Promise<string> => {
  const filters = normalizeAttributeFilters(filter ? [filter] : []);
  const domainSet: string[] = [];
  const suffixSet: string[] = [];
  const keywordSet: string[] = [];
  const regexSet: string[] = [];
  for (const r of data.rules) {
    if (!ruleMatchesAttributes(r, filters)) continue;
    switch (r.type) {
      case "full":
        domainSet.push(r.value);
        break;
      case "domain":
        suffixSet.push(r.value);
        break;
      case "regexp":
        // Try to downgrade simple union regex to keyword list
        const kws = extractSimpleKeywordUnion(r.value);
        if (kws) {
          for (const kw of kws) keywordSet.push(kw);
        } else {
          regexSet.push(r.value);
        }
        break;
    }
  }
  const lines: string[] = [];
  if (domainSet.length > 0) {
    lines.push("domain_set:");
    for (const v of domainSet) lines.push(`  - ${v}`);
  }
  if (suffixSet.length > 0) {
    lines.push("domain_suffix_set:");
    for (const v of suffixSet) lines.push(`  - ${v}`);
  }
  if (keywordSet.length > 0) {
    lines.push("domain_keyword_set:");
    for (const v of keywordSet) lines.push(`  - ${v}`);
  }
  if (regexSet.length > 0) {
    lines.push("domain_regex_set:");
    for (const v of regexSet) lines.push(`  - ${yamlQuote(v)}`);
  }
  return lines.join("\n");
};

const genEgernGeoipYamlFromJson = async (
  data: GeoIPJSON,
  filter: string | null = null
): Promise<string> => {
  const wantV4 = !filter || ["v4", "ipv4"].includes(filter.toLowerCase());
  const wantV6 = !filter || ["v6", "ipv6"].includes(filter.toLowerCase());
  const lines: string[] = [];
  if (wantV4) {
    const list = data.cidr4 || [];
    if (list.length > 0) {
      lines.push("ip_cidr_set:");
      for (const cidr of list) lines.push(`  - ${yamlQuote(cidr)}`);
    }
  }
  if (wantV6) {
    const list6 = data.cidr6 || [];
    if (list6.length > 0) {
      lines.push("ip_cidr6_set:");
      for (const cidr of list6) lines.push(`  - ${yamlQuote(cidr)}`);
    }
  }
  return lines.join("\n");
};

const getGeoipJson = async (name: string, r2?: R2Bucket): Promise<GeoIPJSON | null> => {
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  const now = Date.now();
  cleanupCache(geoipCache, now);
  for (const candidate of candidates) {
    const cached = geoipCache.get(candidate);
    if (cached && cached.expires > now) {
      return cached.data;
    }
  }
  if (r2) {
    for (const n of candidates) {
      const key = `geoip-json/${n}.json`;
      try {
        const obj = await r2.get(key);
        if (!obj) continue;
        let data: GeoIPJSON | null = null;
        try {
          if (typeof (obj as any).json === "function") {
            const parsed = await (obj as any).json();
            if (parsed && typeof parsed === "object") {
              data = parsed as GeoIPJSON;
            }
          }
        } catch (_) {
          // ignore json() errors; fallback to manual parse
        }
        if (!data) {
          const ab = await obj.arrayBuffer();
          const text = new TextDecoder().decode(ab);
          data = JSON.parse(text) as GeoIPJSON;
        }
        if (data && data.name) {
          const expires = Date.now() + GEOIP_CACHE_TTL_MS;
          const variants = Array.from(new Set([...candidates, data.name, data.name.toUpperCase(), data.name.toLowerCase()]));
          for (const variant of variants) {
            geoipCache.set(variant, { data, expires });
          }
          return data;
        }
      } catch (_) {
        // continue to next variant
      }
    }
  }
  return null;
};

const genSurgeIpListFromJson = async (
  data: GeoIPJSON,
  filter: string | null = null
): Promise<string> => {
  const wantV4 = !filter || filter.toLowerCase() === "v4" || filter.toLowerCase() === "ipv4";
  const wantV6 = !filter || filter.toLowerCase() === "v6" || filter.toLowerCase() === "ipv6";
  const lines: string[] = [];
  if (wantV4) {
    for (const cidr of data.cidr4 || []) {
      lines.push(`IP-CIDR,${cidr},no-resolve`);
    }
  }
  if (wantV6) {
    for (const cidr of data.cidr6 || []) {
      lines.push(`IP-CIDR6,${cidr},no-resolve`);
    }
  }
  return lines.join("\n");
};

const normalizeAttributeFilters = (
  input: string | string[] | null | undefined
): string[] => {
  if (input == null) return [];
  const rawItems = Array.isArray(input)
    ? input
    : String(input)
        .split(/[,\s]+/)
        .map((v) => v.trim())
        .filter((v) => v.length > 0);
  const result: string[] = [];
  for (const item of rawItems) {
    let value = item.trim();
    if (!value) continue;
    while (value.startsWith("@")) value = value.slice(1);
    const neg = value.startsWith("!");
    const body = neg ? value.slice(1) : value;
    if (!body) continue;
    const normalized = neg ? `!${body.toLowerCase()}` : body.toLowerCase();
    if (!result.includes(normalized)) result.push(normalized);
  }
  return result;
};

const ruleMatchesAttributes = (rule: RuleItem, filters: string[]): boolean => {
  if (!filters || filters.length === 0) return true;
  const attrs = (rule.attrs || []).map((a) => a.toLowerCase());
  for (const f of filters) {
    const neg = f.startsWith("!");
    const target = (neg ? f.slice(1) : f).toLowerCase();
    if (!target) continue;
    const has = attrs.includes(target);
    if (neg) {
      if (has) return false;
    } else if (!has) {
      return false;
    }
  }
  return true;
};

const summarizeRuleTypes = (rules: RuleItem[]) => {
  const summary = {
    total: rules.length,
    domain: 0,
    full: 0,
    regexp: 0,
  };
  for (const r of rules) {
    if (r.type === "domain") summary.domain++;
    else if (r.type === "full") summary.full++;
    else if (r.type === "regexp") summary.regexp++;
  }
  return summary;
};

const collectRuleAttributes = (rules: RuleItem[]): string[] => {
  const set = new Set<string>();
  for (const rule of rules) {
    for (const attr of rule.attrs || []) {
      if (attr) set.add(attr);
    }
  }
  return Array.from(set).sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }));
};

const splitNameSegments = (name: string): string[] => {
  return name
    .split(/[-:_]/)
    .map((part) => part.trim())
    .filter((part) => part.length > 0);
};

const clamp = (value: number, min: number, max: number): number => {
  if (Number.isNaN(value)) return min;
  if (value < min) return min;
  if (value > max) return max;
  return value;
};

const extractHostCandidate = (raw: string): string => {
  let target = raw.trim();
  if (!target) return "";
  try {
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//.test(target)) {
      const url = new URL(target);
      target = url.hostname || target;
    }
  } catch (_) {
    // ignore URL parse failures
  }
  target = target.replace(/^\*\./, "");
  const slashIndex = target.indexOf("/");
  if (slashIndex >= 0) target = target.slice(0, slashIndex);
  const questionIndex = target.indexOf("?");
  if (questionIndex >= 0) target = target.slice(0, questionIndex);
  target = target.replace(/:\d+$/, "");
  target = target.replace(/\.+$/, "");
  return target.trim().toLowerCase();
};

type GeositeRuleMatchMeta = {
  reason: string;
  score: number;
  matched: string;
};

// Fast evaluation function for suffix-only matching
const evaluateGeositeRuleFast = (
  rule: RuleItem,
  rawQuery: string,
  hostLower: string
): GeositeRuleMatchMeta | null => {
  const value = rule.value.trim();
  const valueLower = value.toLowerCase();

  switch (rule.type) {
    case "full": {
      if (hostLower && hostLower === valueLower) {
        return { reason: "exact host", score: 110, matched: value };
      }
      break;
    }
    case "domain": {
      if (hostLower) {
        if (hostLower === valueLower) {
          return { reason: "domain suffix", score: 105, matched: value };
        }
        if (hostLower.endsWith(`.${valueLower}`)) {
          return { reason: "domain suffix", score: 95, matched: value };
        }
      }
      break;
    }
    // Skip regexp rules in fast search for performance
  }
  return null;
};

const evaluateGeositeRule = (
  rule: RuleItem,
  rawQuery: string,
  hostLower: string,
  queryLower: string
): GeositeRuleMatchMeta | null => {
  const value = rule.value.trim();
  const valueLower = value.toLowerCase();
  switch (rule.type) {
    case "full": {
      if (hostLower && hostLower === valueLower) {
        return { reason: "exact host", score: 110, matched: value };
      }
      if (queryLower && valueLower === queryLower) {
        return { reason: "exact value", score: 90, matched: value };
      }
      if (queryLower && valueLower.includes(queryLower)) {
        return { reason: "value contains", score: 45, matched: value };
      }
      break;
    }
    case "domain": {
      if (hostLower) {
        if (hostLower === valueLower) {
          return { reason: "domain suffix", score: 105, matched: value };
        }
        if (hostLower.endsWith(`.${valueLower}`)) {
          return { reason: "domain suffix", score: 95, matched: value };
        }
      }
      if (queryLower && valueLower.includes(queryLower)) {
        return { reason: "value contains", score: 40, matched: value };
      }
      break;
    }
    case "regexp": {
      try {
        const regex = new RegExp(rule.value, "i");
        if (regex.test(rawQuery)) {
          return { reason: "regex", score: 70, matched: rule.value };
        }
      } catch (_) {
        // ignore invalid regex
      }
      if (queryLower && rule.value.toLowerCase().includes(queryLower)) {
        return { reason: "regex contains", score: 35, matched: rule.value };
      }
      break;
    }
  }
  return null;
};

type GeositeSearchMatch = {
  list: string;
  url?: string;
  rule: RuleItem;
  reason: string;
  score: number;
  matched: string;
};

// Fast search function for suffix-only domain matching
const searchGeositeRulesFast = async (
  query: string,
  attributeFilters: string[],
  _names: string[],
  limit: number,
  env: EnvBindings,
  indexMap: Record<string, string>,
  _maxLists: number
): Promise<{ matches: GeositeSearchMatch[]; scanned: number; searchMode: string }> => {
  const db = ensureDb(env);
  const trimmedQuery = query.trim();
  const hostLower = extractHostCandidate(trimmedQuery).toLowerCase();

  if (!hostLower) {
    return { matches: [], scanned: 0, searchMode: "fast-suffix" };
  }

  // Use exact host and its immediate parent as candidates
  const domainCandidates = new Set<string>([hostLower]);
  const parts = hostLower.split(".");
  if (parts.length > 1) domainCandidates.add(parts.slice(1).join("."));

  const domainValues = Array.from(domainCandidates).filter((item) => item.length > 0);
  const domainRevSet = new Set<string>();
  const legacyDomainValues: string[] = [];
  for (const value of domainValues) {
    const reversed = reverseDomainValue(value);
    if (reversed) domainRevSet.add(reversed);
    else legacyDomainValues.push(value);
  }
  const domainRevValues = Array.from(domainRevSet);

  const overscan = Math.max(limit * 2, limit + 10);
  const matches: GeositeSearchMatch[] = [];
  const seen = new Set<string>();

  const processRows = (rows: any[]) => {
    for (const row of rows) {
      if (!row) continue;
      const rule: RuleItem = {
        type: row.type,
        value: row.value,
        attrs: parseAttrsJson(row.attrs),
      };
      if (!ruleMatchesAttributes(rule, attributeFilters)) continue;
      const meta = evaluateGeositeRuleFast(rule, trimmedQuery, hostLower);
      if (!meta) continue;
      const key = `${row.list}:::${rule.type}:::${rule.value}:::${meta.matched}`;
      if (seen.has(key)) continue;
      seen.add(key);
      matches.push({
        list: row.list,
        url: indexMap[row.list] || undefined,
        rule,
        reason: meta.reason,
        score: meta.score,
        matched: meta.matched,
      });
      if (matches.length >= overscan) return true;
    }
    return false;
  };

  // 1) Try value_rev equals candidates (fastest when indexed)
  const canUseValueRev = geositeValueRevAvailable !== false && domainRevValues.length > 0;
  if (canUseValueRev) {
    const placeholders = domainRevValues.map(() => "?").join(",");
    const sql = `SELECT l.name AS list, r.type, r.value, r.attrs
      FROM geosite_rule r
      JOIN geosite_list l ON l.id = r.list_id
      WHERE r.type IN ('domain','full')
        AND r.value_rev IN (${placeholders})
      LIMIT ${overscan}`;
    try {
      const result = await db.prepare(sql).bind(...domainRevValues).all<any>();
      geositeValueRevAvailable = true;
      processRows(result.results || []);
    } catch (error) {
      if (
        geositeValueRevAvailable !== false &&
        error instanceof Error &&
        /value_rev/i.test(error.message)
      ) {
        geositeValueRevAvailable = false;
      } else {
        throw error;
      }
    }
  }

  // 2) Fallback to value_lower equals candidates when needed
  if (matches.length < overscan) {
    const fallbackValues = geositeValueRevAvailable === false
      ? domainValues
      : domainRevValues.length === 0
        ? domainValues
        : legacyDomainValues;
    if (fallbackValues.length > 0) {
      const placeholders = fallbackValues.map(() => "?").join(",");
      const sql = `SELECT l.name AS list, r.type, r.value, r.attrs
        FROM geosite_rule r
        JOIN geosite_list l ON l.id = r.list_id
        WHERE r.type IN ('domain','full')
          AND r.value_lower IN (${placeholders})
        LIMIT ${overscan}`;
      const result = await db.prepare(sql).bind(...fallbackValues).all<any>();
      processRows(result.results || []);
    }
  }

  // Sort and cap
  matches.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.list.toLowerCase() === b.list.toLowerCase()) {
      return a.rule.value.localeCompare(b.rule.value, "en", { sensitivity: "base" });
    }
    return a.list.localeCompare(b.list, "en", { sensitivity: "base" });
  });

  // scanned: distinct lists surfaced in results (since we didn't iterate lists)
  const scanned = new Set(matches.map((m) => m.list)).size;
  return { matches: matches.slice(0, limit), scanned, searchMode: "fast-suffix" };
};

const searchGeositeRules = async (
  query: string,
  attributeFilters: string[],
  names: string[],
  limit: number,
  env: EnvBindings,
  indexMap: Record<string, string>,
  maxLists: number,
  tokens: string[]
): Promise<{ matches: GeositeSearchMatch[]; scanned: number }> => {
  const db = ensureDb(env);
  const trimmedQuery = query.trim();
  const hostLower = extractHostCandidate(trimmedQuery).toLowerCase();
  const queryLower = trimmedQuery.toLowerCase();
  const domainCandidates = new Set<string>();
  if (hostLower) buildDomainSuffixes(hostLower).forEach((suffix) => domainCandidates.add(suffix.toLowerCase()));
  if (queryLower) domainCandidates.add(queryLower);
  const domainValues = Array.from(domainCandidates).filter((item) => item.length > 0);
  const domainRevSet = new Set<string>();
  const legacyDomainValues: string[] = [];
  for (const value of domainValues) {
    const reversed = reverseDomainValue(value);
    if (reversed) {
      domainRevSet.add(reversed);
    } else {
      legacyDomainValues.push(value);
    }
  }
  const domainRevValues = Array.from(domainRevSet);
  const likePatterns = tokens.map((token) => `%${escapeLikePattern(token)}%`);
  const ftsQuery = buildFtsMatchQuery(tokens);

  const overscan = Math.max(limit * 3, limit + 20);
  const matches: GeositeSearchMatch[] = [];
  const seen = new Set<string>();
  let scanned = 0;
  const maxScan = Math.max(1, Math.min(Math.floor(maxLists) || 1, names.length));
  const chunks = chunkArray(names.slice(0, maxScan), 40);

  const processRows = (rows: any[]) => {
    for (const row of rows) {
      if (!row) continue;
      const rule: RuleItem = {
        type: row.type,
        value: row.value,
        attrs: parseAttrsJson(row.attrs),
      };
      if (!ruleMatchesAttributes(rule, attributeFilters)) continue;
      const meta = evaluateGeositeRule(rule, trimmedQuery, hostLower, queryLower);
      if (!meta) continue;
      const key = `${row.list}:::${rule.type}:::${rule.value}:::${meta.matched}`;
      if (seen.has(key)) continue;
      seen.add(key);
      matches.push({
        list: row.list,
        url: indexMap[row.list] || undefined,
        rule,
        reason: meta.reason,
        score: meta.score,
        matched: meta.matched,
      });
      if (matches.length >= overscan) return true;
    }
    return false;
  };

  for (const chunk of chunks) {
    scanned += chunk.length;
    const namePlaceholders = chunk.map(() => "?").join(",");
    const nameParams = chunk;

    let attemptedValueRev = false;
    const canUseValueRev = geositeValueRevAvailable !== false && domainRevValues.length > 0;
    if (canUseValueRev) {
      const domainPlaceholders = domainRevValues.map(() => "?").join(",");
      const sql = `SELECT l.name AS list, r.type, r.value, r.attrs\n        FROM geosite_rule r\n        JOIN geosite_list l ON l.id = r.list_id\n        WHERE l.name IN (${namePlaceholders})\n          AND r.type IN ('domain','full')\n          AND r.value_rev IN (${domainPlaceholders})`;
      try {
        const result = await db.prepare(sql).bind(...nameParams, ...domainRevValues).all<any>();
        geositeValueRevAvailable = true;
        attemptedValueRev = true;
        if (processRows(result.results || [])) break;
      } catch (error) {
        if (
          geositeValueRevAvailable !== false &&
          error instanceof Error &&
          /value_rev/i.test(error.message)
        ) {
          geositeValueRevAvailable = false;
        } else {
          throw error;
        }
      }
    }

    const shouldFallbackToLower =
      geositeValueRevAvailable === false ||
      (!attemptedValueRev && domainValues.length > 0) ||
      (geositeValueRevAvailable !== false && legacyDomainValues.length > 0);

    if (shouldFallbackToLower) {
      const fallbackValues = geositeValueRevAvailable === false
        ? domainValues
        : domainRevValues.length === 0
          ? domainValues
          : legacyDomainValues;
      if (fallbackValues.length > 0) {
        const domainPlaceholders = fallbackValues.map(() => "?").join(",");
        const sql = `SELECT l.name AS list, r.type, r.value, r.attrs\n          FROM geosite_rule r\n          JOIN geosite_list l ON l.id = r.list_id\n          WHERE l.name IN (${namePlaceholders})\n            AND r.type IN ('domain','full')\n            AND r.value_lower IN (${domainPlaceholders})`;
        const result = await db.prepare(sql).bind(...nameParams, ...fallbackValues).all<any>();
        if (processRows(result.results || [])) break;
      }
    }

    if (ftsQuery && geositeFtsAvailable !== false) {
      const ftsLimit = Math.min(overscan, Math.max(limit * 2, chunk.length * 40));
      const sql = `SELECT l.name AS list, r.type, r.value, r.attrs, bm25(geosite_rule_fts) AS rank\n        FROM geosite_rule_fts\n        JOIN geosite_rule r ON r.rowid = geosite_rule_fts.rowid\n        JOIN geosite_list l ON l.id = r.list_id\n        WHERE l.name IN (${namePlaceholders})\n          AND geosite_rule_fts MATCH ?\n        ORDER BY rank\n        LIMIT ${ftsLimit}`;
      try {
        const result = await db.prepare(sql).bind(...nameParams, ftsQuery).all<any>();
        geositeFtsAvailable = true;
        if (processRows(result.results || [])) break;
      } catch (error) {
        if (
          geositeFtsAvailable !== false &&
          error instanceof Error &&
          /geosite_rule_fts/i.test(error.message)
        ) {
          geositeFtsAvailable = false;
        } else {
          throw error;
        }
      }
    }

    const shouldRunLike = !ftsQuery || geositeFtsAvailable === false;
    if (shouldRunLike) {
      if (likePatterns.length > 0) {
        // 1) Fuzzy match domain/full by value substring to surface common cases like "binance"
        for (const pattern of likePatterns) {
          const sql = `SELECT l.name AS list, r.type, r.value, r.attrs\n            FROM geosite_rule r\n            JOIN geosite_list l ON l.id = r.list_id\n            WHERE l.name IN (${namePlaceholders})\n              AND r.type IN ('domain','full')\n              AND r.value_lower LIKE ? ESCAPE '\\'\n            LIMIT ${chunk.length * 40}`;
          const result = await db.prepare(sql).bind(...nameParams, pattern).all<any>();
          if (processRows(result.results || [])) break;
        }

        // 2) Also allow regexp rules to match by substring as before
        if (matches.length < overscan) {
          for (const pattern of likePatterns) {
            const sql = `SELECT l.name AS list, r.type, r.value, r.attrs\n              FROM geosite_rule r\n              JOIN geosite_list l ON l.id = r.list_id\n              WHERE l.name IN (${namePlaceholders})\n                AND r.type = 'regexp'\n                AND r.value_lower LIKE ? ESCAPE '\\'\n              LIMIT ${chunk.length * 20}`;
            const result = await db.prepare(sql).bind(...nameParams, pattern).all<any>();
            if (processRows(result.results || [])) break;
          }
        }
      } else {
        // No tokens derived; keep a conservative fallback on regexp
        const sql = `SELECT l.name AS list, r.type, r.value, r.attrs\n          FROM geosite_rule r\n          JOIN geosite_list l ON l.id = r.list_id\n          WHERE l.name IN (${namePlaceholders})\n            AND r.type = 'regexp'\n          LIMIT ${chunk.length * 10}`;
        const result = await db.prepare(sql).bind(...nameParams).all<any>();
        if (processRows(result.results || [])) break;
      }
    }

    if (matches.length >= overscan) break;
  }

  matches.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.list.toLowerCase() === b.list.toLowerCase()) {
      return a.rule.value.localeCompare(b.rule.value, "en", { sensitivity: "base" });
    }
    return a.list.localeCompare(b.list, "en", { sensitivity: "base" });
  });

  return { matches: matches.slice(0, limit), scanned };
};

type ParsedIPv4 = { version: "ipv4"; value: number };
type ParsedIPv6 = { version: "ipv6"; value: bigint };
type ParsedIP = ParsedIPv4 | ParsedIPv6;

const parseIPv4Address = (input: string): number | null => {
  const parts = input.split(".");
  if (parts.length !== 4) return null;
  let value = 0;
  for (const part of parts) {
    if (!/^\d+$/.test(part)) return null;
    const octet = Number(part);
    if (octet < 0 || octet > 255) return null;
    value = (value << 8) | octet;
  }
  return value >>> 0;
};

const parseIPv6Address = (input: string): bigint | null => {
  const trimmed = input.trim();
  if (!trimmed) return null;
  const lower = trimmed.toLowerCase();
  const doubleColonIndex = lower.indexOf("::");
  let headParts: string[] = [];
  let tailParts: string[] = [];
  if (doubleColonIndex >= 0) {
    headParts = lower.slice(0, doubleColonIndex).split(":").filter((p) => p.length > 0);
    tailParts = lower.slice(doubleColonIndex + 2).split(":").filter((p) => p.length > 0);
  } else {
    headParts = lower.split(":").filter((p) => p.length > 0);
    tailParts = [];
  }

  const hextets: number[] = [];
  const pushPart = (part: string) => {
    if (part.includes(".")) {
      const ipv4 = parseIPv4Address(part);
      if (ipv4 === null) return false;
      hextets.push((ipv4 >>> 16) & 0xffff, ipv4 & 0xffff);
      return true;
    }
    if (part.length === 0) {
      hextets.push(0);
      return true;
    }
    const value = parseInt(part, 16);
    if (Number.isNaN(value) || value < 0 || value > 0xffff) return false;
    hextets.push(value);
    return true;
  };

  for (const part of headParts) {
    if (!pushPart(part)) return null;
  }

  if (doubleColonIndex >= 0) {
    const missing = 8 - (headParts.length + tailParts.length);
    if (missing < 0) return null;
    for (let i = 0; i < missing; i++) hextets.push(0);
  }

  for (const part of tailParts) {
    if (!pushPart(part)) return null;
  }

  if (doubleColonIndex < 0 && hextets.length !== 8) {
    return null;
  }
  if (hextets.length !== 8) {
    return null;
  }

  let value = 0n;
  for (const h of hextets) {
    value = (value << 16n) | BigInt(h);
  }
  return value;
};

const parseIPAddress = (input: string): ParsedIP | null => {
  const trimmed = input.trim();
  if (!trimmed) return null;
  if (trimmed.includes(".")) {
    const ipv4 = parseIPv4Address(trimmed);
    if (ipv4 !== null) return { version: "ipv4", value: ipv4 };
  }
  if (trimmed.includes(":")) {
    const ipv6 = parseIPv6Address(trimmed);
    if (ipv6 !== null) return { version: "ipv6", value: ipv6 };
  }
  return null;
};


type GeoipSearchMatch = {
  list: string;
  url?: string;
  version: "ipv4" | "ipv6";
  cidr: string;
  prefix: number;
  score: number;
};

const searchGeoipLists = async (
  query: string,
  names: string[],
  limit: number,
  env: EnvBindings,
  indexMap: Record<string, string>,
  maxLists: number
): Promise<{ matches: GeoipSearchMatch[]; scanned: number; mode: string }> => {
  const db = ensureDb(env);
  const trimmed = query.trim();
  const ip = parseIPAddress(trimmed);
  const lower = trimmed.toLowerCase();
  const normalizedCidr = lower;
  const overscan = Math.max(limit * 3, limit + 20);
  const matches: GeoipSearchMatch[] = [];
  const seen = new Set<string>();
  let scanned = 0;
  const maxScan = Math.max(1, Math.min(Math.floor(maxLists) || 1, names.length));
  const chunks = chunkArray(names.slice(0, maxScan), 40);
  const mode = ip ? "ip" : trimmed.includes("/") ? "cidr" : "unknown";

  const totalLists = Object.keys(indexMap).length;
  const hasScope = names.length > 0 && names.length < totalLists;
  const canSingleIn = hasScope && names.length <= 300;

  const pushMatch = (row: any, versionLabel: "ipv4" | "ipv6") => {
    const listName = String(row.list);
    const cidr = String(row.cidr);
    const key = `${listName}:::${cidr}`;
    if (seen.has(key)) return false;
    seen.add(key);
    const prefix = Number(row.prefix || 0);
    matches.push({
      list: listName,
      url: indexMap[listName] || undefined,
      version: versionLabel,
      cidr,
      prefix,
      score: prefix + (versionLabel === "ipv4" ? 1000 : 500),
    });
    return matches.length >= overscan;
  };

  // Fast path: exact IP match across all lists (or a single IN clause when scoped)
  if (ip) {
    if (!hasScope) {
      if (ip.version === "ipv4") {
        const sql = `SELECT l.name AS list, c.cidr, c.prefix
          FROM geoip_cidr c
          JOIN geoip_list l ON l.id = c.list_id
          WHERE c.version = 4
            AND c.start_v4 <= ?
            AND c.end_v4 >= ?
          ORDER BY c.prefix DESC
          LIMIT ${overscan}`;
        const rows = await db.prepare(sql).bind(ip.value, ip.value).all<any>();
        for (const row of rows.results || []) { if (pushMatch(row, "ipv4")) break; }
      } else {
        const ipHex = bigIntToHex(ip.value);
        const sql = `SELECT l.name AS list, c.cidr, c.prefix
          FROM geoip_cidr c
          JOIN geoip_list l ON l.id = c.list_id
          WHERE c.version = 6
            AND c.start_hex <= ?
            AND c.end_hex >= ?
          ORDER BY c.prefix DESC
          LIMIT ${overscan}`;
        const rows = await db.prepare(sql).bind(ipHex, ipHex).all<any>();
        for (const row of rows.results || []) { if (pushMatch(row, "ipv6")) break; }
      }
      scanned = totalLists; // Consider scanned as full-scope
      return { matches: matches.slice(0, limit), scanned, mode };
    } else if (canSingleIn) {
      const namePlaceholders = names.map(() => "?").join(",");
      const nameParams = names;
      if (ip.version === "ipv4") {
        const sql = `SELECT l.name AS list, c.cidr, c.prefix
          FROM geoip_cidr c
          JOIN geoip_list l ON l.id = c.list_id
          WHERE l.name IN (${namePlaceholders})
            AND c.version = 4
            AND c.start_v4 <= ?
            AND c.end_v4 >= ?
          ORDER BY c.prefix DESC
          LIMIT ${overscan}`;
        const rows = await db.prepare(sql).bind(...nameParams, ip.value, ip.value).all<any>();
        for (const row of rows.results || []) { if (pushMatch(row, "ipv4")) break; }
      } else {
        const ipHex = bigIntToHex(ip.value);
        const sql = `SELECT l.name AS list, c.cidr, c.prefix
          FROM geoip_cidr c
          JOIN geoip_list l ON l.id = c.list_id
          WHERE l.name IN (${namePlaceholders})
            AND c.version = 6
            AND c.start_hex <= ?
            AND c.end_hex >= ?
          ORDER BY c.prefix DESC
          LIMIT ${overscan}`;
        const rows = await db.prepare(sql).bind(...nameParams, ipHex, ipHex).all<any>();
        for (const row of rows.results || []) { if (pushMatch(row, "ipv6")) break; }
      }
      scanned = names.length;
      return { matches: matches.slice(0, limit), scanned, mode };
    }
    // else fall through to chunked path below when too many names
  }
  // Fast path: exact CIDR match across all lists (or a single IN clause when scoped)
  if (!ip && trimmed.includes("/")) {
    if (!hasScope) {
      const sql = `SELECT l.name AS list, c.cidr, c.prefix, c.version
        FROM geoip_cidr c
        JOIN geoip_list l ON l.id = c.list_id
        WHERE c.cidr_lower = ?`;
      const rows = await db.prepare(sql).bind(normalizedCidr).all<any>();
      for (const row of rows.results || []) {
        const versionLabel = Number(row.version) === 4 ? "ipv4" : "ipv6";
        if (pushMatch(row, versionLabel)) break;
      }
      scanned = totalLists;
      return { matches: matches.slice(0, limit), scanned, mode };
    } else if (canSingleIn) {
      const namePlaceholders = names.map(() => "?").join(",");
      const nameParams = names;
      const sql = `SELECT l.name AS list, c.cidr, c.prefix, c.version
        FROM geoip_cidr c
        JOIN geoip_list l ON l.id = c.list_id
        WHERE l.name IN (${namePlaceholders})
          AND c.cidr_lower = ?`;
      const rows = await db.prepare(sql).bind(...nameParams, normalizedCidr).all<any>();
      for (const row of rows.results || []) {
        const versionLabel = Number(row.version) === 4 ? "ipv4" : "ipv6";
        if (pushMatch(row, versionLabel)) break;
      }
      scanned = names.length;
      return { matches: matches.slice(0, limit), scanned, mode };
    }
  }

  for (const chunk of chunks) {
    scanned += chunk.length;
    const namePlaceholders = chunk.map(() => "?").join(",");
    const nameParams = chunk;

    if (ip && ip.version === "ipv4") {
      const sql = `SELECT l.name AS list, c.cidr, c.prefix\n        FROM geoip_cidr c\n        JOIN geoip_list l ON l.id = c.list_id\n        WHERE l.name IN (${namePlaceholders})\n          AND c.version = 4\n          AND c.start_v4 <= ?\n          AND c.end_v4 >= ?\n        ORDER BY c.prefix DESC\n        LIMIT ${chunk.length * 80}`;
      const rows = await db.prepare(sql).bind(...nameParams, ip.value, ip.value).all<any>();
      if ((rows.results || []).some((row) => pushMatch(row, "ipv4"))) break;
    }

    if (ip && ip.version === "ipv6") {
      const ipHex = bigIntToHex(ip.value);
      const sql = `SELECT l.name AS list, c.cidr, c.prefix\n        FROM geoip_cidr c\n        JOIN geoip_list l ON l.id = c.list_id\n        WHERE l.name IN (${namePlaceholders})\n          AND c.version = 6\n          AND c.start_hex <= ?\n          AND c.end_hex >= ?\n        ORDER BY c.prefix DESC\n        LIMIT ${chunk.length * 80}`;
      const rows = await db.prepare(sql).bind(...nameParams, ipHex, ipHex).all<any>();
      if ((rows.results || []).some((row) => pushMatch(row, "ipv6"))) break;
    }

    // Exact CIDR within chunk when too many names for single IN
    if (!ip && trimmed.includes("/")) {
      let handledExact = false;
      if (geoipCidrLowerAvailable !== false) {
        const sql = `SELECT l.name AS list, c.cidr, c.prefix, c.version\n          FROM geoip_cidr c\n          JOIN geoip_list l ON l.id = c.list_id\n          WHERE l.name IN (${namePlaceholders})\n            AND c.cidr_lower = ?`;
        try {
          const rows = await db.prepare(sql).bind(...nameParams, normalizedCidr).all<any>();
          geoipCidrLowerAvailable = true;
          handledExact = true;
          for (const row of rows.results || []) {
            const versionLabel = Number(row.version) === 4 ? "ipv4" : "ipv6";
            if (pushMatch(row, versionLabel)) break;
          }
        } catch (error) {
          if (
            geoipCidrLowerAvailable !== false &&
            error instanceof Error &&
            /cidr_lower/i.test(error.message)
          ) {
            geoipCidrLowerAvailable = false;
          } else {
            throw error;
          }
        }
      }

      if (!handledExact) {
        const sql = `SELECT l.name AS list, c.cidr, c.prefix, c.version\n          FROM geoip_cidr c\n          JOIN geoip_list l ON l.id = c.list_id\n          WHERE l.name IN (${namePlaceholders})\n            AND LOWER(c.cidr) = LOWER(?)`;
        const rows = await db.prepare(sql).bind(...nameParams, trimmed).all<any>();
        for (const row of rows.results || []) {
          const versionLabel = Number(row.version) === 4 ? "ipv4" : "ipv6";
          if (pushMatch(row, versionLabel)) break;
        }
      }
    }

    if (matches.length >= overscan) break;
  }

  matches.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (a.list.toLowerCase() === b.list.toLowerCase()) {
      return a.cidr.localeCompare(b.cidr, "en", { sensitivity: "base" });
    }
    return a.list.localeCompare(b.list, "en", { sensitivity: "base" });
  });

  return { matches: matches.slice(0, limit), scanned, mode };
};

// SRS distribution via R2
const getSrsKey = (name: string, filter: string | null): string => {
  // Store keys under geosite/ prefix for organization; '!' allowed in keys
  const fname = filter ? `${name}@${filter}.srs` : `${name}.srs`;
  return `geosite/${fname}`;
};

const getGeoipSrsKey = (name: string, filter: string | null): string => {
  // Store GeoIP SRS under geoip/ prefix
  const fname = filter ? `${name}@${filter}.srs` : `${name}.srs`;
  return `geoip/${fname}`;
};

// MRS distribution via R2
const getMrsKey = (name: string, filter: string | null): string => {
  // Store MRS keys under geosite/ prefix alongside SRS files
  const fname = filter ? `${name}@${filter}.mrs` : `${name}.mrs`;
  return `geosite/${fname}`;
};

const getGeoipMrsKey = (name: string, filter: string | null): string => {
  // Store GeoIP MRS under geoip/ prefix alongside SRS files
  const fname = filter ? `${name}@${filter}.mrs` : `${name}.mrs`;
  return `geoip/${fname}`;
};

app.get("/srs/:name_with_filter", async (c) => {
  let raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  // Require ".srs" suffix in URL, e.g. /srs/APPLE.srs or /srs/APPLE@cn.srs
  if (!raw.toLowerCase().endsWith(".srs")) {
    throw new HTTPException(404, { message: "Not found" });
  }
  raw = raw.slice(0, -4);
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName; // keep original case
  const filter = rawFilter ? rawFilter.toLowerCase() : null; // attributes are lowercase like cn

  const bucket = (c as any).env?.SRS_BUCKET as R2Bucket | undefined;
  if (!bucket) {
    throw new HTTPException(500, { message: "SRS bucket not configured" });
  }
  const candidates = Array.from(
    new Set([
      name,
      name.toUpperCase(),
      name.toLowerCase(),
    ])
  );
  let found: R2ObjectBody | null = null;
  let pickedKey = "";
  for (const n of candidates) {
    const key = getSrsKey(n, filter);
    const obj = await bucket.get(key);
    if (obj) {
      found = obj;
      pickedKey = key;
      break;
    }
  }
  const obj = found;
  if (!obj) {
    throw new HTTPException(404, { message: "SRS not found" });
  }
  const headers = new Headers();
  headers.set("content-type", "application/octet-stream");
  const suggested = pickedKey.split("/").pop() || pickedKey;
  headers.set("content-disposition", `inline; filename="${encodeURIComponent(suggested)}"`);
  if (obj.etag) headers.set("etag", obj.etag);
  return new Response(obj.body, { headers });
});

// Alias: /srs-geosite mirrors /srs for geosite SRS objects
app.get("/srs-geosite/:name_with_filter", async (c) => {
  let raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  if (!raw.toLowerCase().endsWith(".srs")) {
    throw new HTTPException(404, { message: "Not found" });
  }
  raw = raw.slice(0, -4);
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null;

  const bucket = (c as any).env?.SRS_BUCKET as R2Bucket | undefined;
  if (!bucket) {
    throw new HTTPException(500, { message: "SRS bucket not configured" });
  }
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  let found: R2ObjectBody | null = null;
  let pickedKey = "";
  for (const n of candidates) {
    const key = getSrsKey(n, filter);
    const obj = await bucket.get(key);
    if (obj) {
      found = obj;
      pickedKey = key;
      break;
    }
  }
  const obj = found;
  if (!obj) {
    throw new HTTPException(404, { message: "SRS not found" });
  }
  const headers = new Headers();
  headers.set("content-type", "application/octet-stream");
  const suggested = pickedKey.split("/").pop() || pickedKey;
  headers.set("content-disposition", `inline; filename="${encodeURIComponent(suggested)}"`);
  if (obj.etag) headers.set("etag", obj.etag);
  return new Response(obj.body, { headers });
});

// MRS geosite endpoint
app.get("/mihomo/geosite/:name_with_filter", async (c) => {
  let raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  // Require ".mrs" suffix in URL, e.g. /mrs-geosite/APPLE.mrs or /mrs-geosite/APPLE@cn.mrs
  if (!raw.toLowerCase().endsWith(".mrs")) {
    throw new HTTPException(404, { message: "Not found" });
  }
  raw = raw.slice(0, -4);
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null;

  const bucket = (c as any).env?.SRS_BUCKET as R2Bucket | undefined;
  if (!bucket) {
    throw new HTTPException(500, { message: "MRS bucket not configured" });
  }
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  let found: R2ObjectBody | null = null;
  let pickedKey = "";
  for (const n of candidates) {
    const key = getMrsKey(n, filter);
    const obj = await bucket.get(key);
    if (obj) {
      found = obj;
      pickedKey = key;
      break;
    }
  }

  const obj = found;
  if (!obj) {
    throw new HTTPException(404, { message: "MRS not found" });
  }

  const headers = new Headers();
  headers.set("content-type", "application/octet-stream");
  const suggested = pickedKey.split("/").pop() || pickedKey;
  headers.set("content-disposition", `inline; filename="${encodeURIComponent(suggested)}"`);
  if (obj.etag) headers.set("etag", obj.etag);
  return new Response(obj.body, { headers });
});

app.get("/geosite/:name_with_filter", async (c) => {
  const raw = c.req.param("name_with_filter").trim();

  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }

  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName; // keep original case; we try variants when fetching JSON
  const filter = rawFilter ? rawFilter.toLowerCase() : null; // attributes are lowercase like cn

  if (!name || name.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }

  try {
    // Only use prebuilt JSON rules (no v2fly fallback)
    const jsonRules = await getJsonRules(name, (c as any).env?.SRS_BUCKET);
    if (!jsonRules) {
      throw new HTTPException(404, { message: "Rules not found (JSON missing)" });
    }
    const surgeList = await genSurgeListFromJson(jsonRules, filter);
    return c.text(surgeList);
  } catch (error) {
    console.error(`Error processing ${raw}:`, error);
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to process request: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

// Egern rule-set (geosite) YAML
app.get("/egern/geosite/:name_with_filter", async (c) => {
  const raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null;
  try {
    const jsonRules = await getJsonRules(name, (c as any).env?.SRS_BUCKET);
    if (!jsonRules) {
      throw new HTTPException(404, { message: "Rules not found (JSON missing)" });
    }
    const yaml = await genEgernGeositeYamlFromJson(jsonRules, filter);
    const headers = new Headers();
    headers.set("content-type", "text/yaml; charset=utf-8");
    headers.set("cache-control", "public, max-age=300, s-maxage=1800");
    const filename = `${jsonRules.name}${filter ? `@${filter}` : ""}.yaml`;
    headers.set("content-disposition", `inline; filename="${encodeURIComponent(filename)}"`);
    return new Response(yaml, { headers });
  } catch (error) {
    console.error(`Error processing egern geosite ${raw}:`, error);
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to process request: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

app.get("/geosite", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  const bypassKv = c.req.query("fresh") === "1";
  try {
    const data = await fetchIndexMap("geosite", env, bypassKv);
    return c.json(data);
  } catch (error) {
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to load geosite index: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

app.get("/api/geosite/:name", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  const rawName = c.req.param("name")?.trim();
  if (!rawName) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }

  // Parse pagination parameters
  const offset = Math.max(0, parseInt(c.req.query("offset") || "0", 10));
  const limit = clamp(parseInt(c.req.query("limit") || "1000", 10), 10, 2000);
  const search = c.req.query("search")?.trim() || "";

  const filters = normalizeAttributeFilters(c.req.query("filter"));
  const data = await getJsonRules(rawName, env.SRS_BUCKET);
  if (!data) {
    throw new HTTPException(404, { message: "Rules not found (JSON missing)" });
  }

  // Apply attribute filters first
  let filtered = filters.length > 0 ? data.rules.filter((rule) => ruleMatchesAttributes(rule, filters)) : data.rules;

  // Apply search filter if provided
  if (search) {
    const searchLower = search.toLowerCase();
    filtered = filtered.filter((rule) => {
      const combined = (rule.type + " " + rule.value + " " + (rule.attrs || []).join(" ")).toLowerCase();
      return combined.includes(searchLower);
    });
  }

  // Calculate pagination
  const total = filtered.length;
  const paginatedRules = filtered.slice(offset, offset + limit);
  const hasMore = offset + limit < total;

  const indexMap = await fetchIndexMap("geosite", env).catch(() => ({} as Record<string, string>));
  const statsOverall = summarizeRuleTypes(data.rules);
  const statsFiltered = summarizeRuleTypes(filtered);
  const attrs = collectRuleAttributes(data.rules);
  const canonicalUrl = indexMap[data.name] || indexMap[rawName] || null;

  const response = c.json({
    name: data.name,
    requested: rawName,
    url: canonicalUrl,
    segments: splitNameSegments(data.name),
    filters,
    search,
    pagination: {
      offset,
      limit,
      total,
      hasMore,
      returned: paginatedRules.length,
    },
    stats: {
      overall: statsOverall,
      filtered: statsFiltered,
    },
    attributes: attrs,
    rules: paginatedRules,
  });

  // Add caching headers for better performance
  response.headers.set('Cache-Control', 'public, max-age=300, s-maxage=1800'); // 5min browser, 30min CDN
  response.headers.set('Vary', 'Accept-Encoding');

  return response;
});

app.get("/geoip/:name_with_filter", async (c) => {
  const raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null; // supports v4/v6

  try {
    const json = await getGeoipJson(name, (c as any).env?.SRS_BUCKET);
    if (!json) {
      throw new HTTPException(404, { message: "GeoIP not found (JSON missing)" });
    }
    const surgeList = await genSurgeIpListFromJson(json, filter);
    return c.text(surgeList);
  } catch (error) {
    console.error(`Error processing geoip ${raw}:`, error);
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to process request: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

// Egern rule-set (geoip) YAML
app.get("/egern/geoip/:name_with_filter", async (c) => {
  const raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null;
  try {
    const json = await getGeoipJson(name, (c as any).env?.SRS_BUCKET);
    if (!json) {
      throw new HTTPException(404, { message: "GeoIP not found (JSON missing)" });
    }
    const yaml = await genEgernGeoipYamlFromJson(json, filter);
    const headers = new Headers();
    headers.set("content-type", "text/yaml; charset=utf-8");
    headers.set("cache-control", "public, max-age=300, s-maxage=1800");
    const filename = `${json.name}${filter ? `@${filter}` : ""}.yaml`;
    headers.set("content-disposition", `inline; filename="${encodeURIComponent(filename)}"`);
    return new Response(yaml, { headers });
  } catch (error) {
    console.error(`Error processing egern geoip ${raw}:`, error);
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to process request: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

app.get("/geoip", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  const bypassKv = c.req.query("fresh") === "1";
  try {
    const data = await fetchIndexMap("geoip", env, bypassKv);
    return c.json(data);
  } catch (error) {
    if (error instanceof HTTPException) throw error;
    throw new HTTPException(500, {
      message: `Failed to load geoip index: ${error instanceof Error ? error.message : "Unknown error"}`,
    });
  }
});

app.get("/api/geoip/:name", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  const rawName = c.req.param("name")?.trim();
  if (!rawName) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  const filter = c.req.query("filter");
  const data = await getGeoipJson(rawName, env.SRS_BUCKET);
  if (!data) {
    throw new HTTPException(404, { message: "GeoIP not found (JSON missing)" });
  }
  const wantV4 = !filter || ["v4", "ipv4"].includes(filter.toLowerCase());
  const wantV6 = !filter || ["v6", "ipv6"].includes(filter.toLowerCase());
  const cidr4 = wantV4 ? data.cidr4 || [] : [];
  const cidr6 = wantV6 ? data.cidr6 || [] : [];
  const indexMap = await fetchIndexMap("geoip", env).catch(() => ({} as Record<string, string>));
  const canonicalUrl = indexMap[data.name] || indexMap[rawName] || null;
  return c.json({
    name: data.name,
    requested: rawName,
    url: canonicalUrl,
    segments: splitNameSegments(data.name),
    filter: filter || null,
    stats: {
      totalV4: data.cidr4?.length || 0,
      totalV6: data.cidr6?.length || 0,
      returnedV4: cidr4.length,
      returnedV6: cidr6.length,
    },
    cidr4,
    cidr6,
  });
});

app.post("/api/search/geosite", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  let payload: any;
  try {
    payload = await c.req.json();
  } catch (error) {
    throw new HTTPException(400, { message: "Invalid JSON payload" });
  }
  const query = String(payload?.query ?? "").trim();
  if (!query) {
    throw new HTTPException(400, { message: "Missing query" });
  }
  const filters = normalizeAttributeFilters(payload?.attributes ?? payload?.filter);

  // Try KV cache for hot queries (comprehensive geosite search)
  const kv = env.GEO_KV;
  const listsParam = clamp(Number(payload?.lists ?? 600), 100, 2000);
  const limitParam = clamp(Number(payload?.limit ?? 200), 5, 200); // default widened to 200
  const namesParam: string[] = Array.isArray(payload?.names)
    ? payload.names.map((n: unknown) => String(n).trim()).filter((n: string) => n.length > 0)
    : [];
  const namesKeyPart = namesParam.length ? `|names=${namesParam.sort((a,b)=>a.localeCompare(b)).join(";")}` : "";
  const cacheKey = kv
    ? `search:geosite:v1:q=${query.toLowerCase()}|f=${filters.join(",")}|lmt=${limitParam}|lists=${listsParam}${namesKeyPart}`
    : null;
  if (kv && cacheKey) {
    try {
      const kvStart = Date.now();
      const cached = (await kv.get(cacheKey, { type: "json" })) as any | null;
      if (cached && typeof cached === "object" && Array.isArray(cached.matches)) {
        const now = Date.now();
        const genAt = Number((cached as any).generatedAt || 0);
        const softSec = Number((cached as any).softTtlSec || SEARCH_SOFT_TTL_SECONDS);
        const isFresh = genAt > 0 && (now - genAt) <= softSec * 1000;

        if (!isFresh) {
          // Background revalidation with a simple lock to avoid stampede
          const lockKey = `${cacheKey}:lock`;
          schedule(c, (async () => {
            try {
              const hasLock = await kv.get(lockKey);
              if (hasLock) return;
              await kv.put(lockKey, "1", { expirationTtl: 60 });

              const indexMapBg = await fetchIndexMap("geosite", env);
              const totalAvailableBg = Object.keys(indexMapBg).length;
              const scopedNamesBg = namesParam.length
                ? namesParam.filter((name) => indexMapBg[name] !== undefined)
                : Object.keys(indexMapBg);
              if (scopedNamesBg.length === 0) return;
              const tokensBg = buildSearchTokens(query);
              const prioritizedBg = tokensBg.length
                ? scopedNamesBg.filter((name) => {
                    const lower = name.toLowerCase();
                    return tokensBg.some((token) => lower.includes(token));
                  })
                : [];
              const dedupedNamesBg = Array.from(new Map([...prioritizedBg, ...scopedNamesBg].map((n) => [n, n])).values());
              const namesForSearchBg = dedupedNamesBg.slice(0, Math.min(listsParam, dedupedNamesBg.length));
              const { matches: matchesBg, scanned: scannedBg } = await searchGeositeRules(
                query,
                filters,
                namesForSearchBg,
                limitParam,
                env,
                indexMapBg,
                namesForSearchBg.length,
                tokensBg
              );
              const responseBodyBg = {
                query,
                filters,
                limit: limitParam,
                scope: {
                  requested: namesParam,
                  used: namesForSearchBg.length,
                  total: totalAvailableBg,
                  scanned: scannedBg,
                  prioritized: prioritizedBg,
                },
                matches: matchesBg,
                searchMode: "comprehensive",
                generatedAt: Date.now(),
                softTtlSec: SEARCH_SOFT_TTL_SECONDS,
              };
              const eq = JSON.stringify({ q: cached.query, f: cached.filters, l: cached.limit, m: cached.matches }) ===
                        JSON.stringify({ q: responseBodyBg.query, f: responseBodyBg.filters, l: responseBodyBg.limit, m: responseBodyBg.matches });
              if (!eq) {
                await kv.put(cacheKey, JSON.stringify(responseBodyBg), { expirationTtl: SEARCH_KV_TTL_SECONDS });
              } else if (!genAt) {
                // Backfill metadata for old entries
                await kv.put(cacheKey, JSON.stringify(responseBodyBg), { expirationTtl: SEARCH_KV_TTL_SECONDS });
              }
            } catch (_) { /* ignore */ }
          })());
        }

        c.header("X-Cache-Status", "HIT-KV");
        c.header("Cache-Control", "no-store");
        const kvElapsed = Date.now() - kvStart;
        const withPerf = {
          ...cached,
          performance: {
            searchTimeMs: kvElapsed,
            avgTimePerList: 0,
          },
        };
        return c.json(withPerf);
      }
    } catch (_) {
      // ignore KV errors
    }
  }
  const indexMap = await fetchIndexMap("geosite", env);
  const totalAvailable = Object.keys(indexMap).length;
  const requestedNames: string[] = namesParam;
  const scopedNames = requestedNames.length
    ? requestedNames.filter((name) => indexMap[name] !== undefined)
    : Object.keys(indexMap);
  if (scopedNames.length === 0) {
    throw new HTTPException(400, { message: "No valid geosite names in scope" });
  }
  const limit = limitParam;
  const tokens = buildSearchTokens(query);
  const prioritized = tokens.length
    ? scopedNames.filter((name) => {
        const lower = name.toLowerCase();
        return tokens.some((token) => lower.includes(token));
      })
    : [];
  const maxLists = listsParam;
  const dedupedNames = Array.from(new Map([...prioritized, ...scopedNames].map((n) => [n, n])).values());
  const namesForSearch = dedupedNames.slice(0, Math.min(maxLists, dedupedNames.length));
  const startTime = Date.now();
  const { matches, scanned } = await searchGeositeRules(
    query,
    filters,
    namesForSearch,
    limit,
    env,
    indexMap,
    namesForSearch.length,
    tokens
  );
  const searchTime = Date.now() - startTime;

  const responseBody = {
    query,
    filters,
    limit,
    scope: {
      requested: requestedNames,
      used: namesForSearch.length,
      total: totalAvailable,
      scanned,
      prioritized,
    },
    matches,
    searchMode: "comprehensive",
    performance: {
      searchTimeMs: searchTime,
      avgTimePerList: namesForSearch.length > 0 ? Math.round((searchTime / namesForSearch.length) * 100) / 100 : 0,
    },
    generatedAt: Date.now(),
    softTtlSec: SEARCH_SOFT_TTL_SECONDS,
  };

  // Populate KV cache (do not cache performance/timing)
  if (kv && cacheKey) {
    try {
      const { performance: _perf, ...responseBodyNoPerf } = responseBody as any;
      await kv.put(cacheKey, JSON.stringify(responseBodyNoPerf), { expirationTtl: SEARCH_KV_TTL_SECONDS });
      c.header("X-Cache-Status", "MISS-KV");
    } catch (_) {
      // ignore KV errors
    }
  }

  c.status(200);
  c.header("Cache-Control", "no-store");
  return c.json(responseBody);
});

app.post("/api/search/geosite/fast", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  let payload: any;
  try {
    payload = await c.req.json();
  } catch (error) {
    throw new HTTPException(400, { message: "Invalid JSON payload" });
  }
  const query = String(payload?.query ?? "").trim();
  if (!query) {
    throw new HTTPException(400, { message: "Missing query" });
  }

  // Validate that query looks like a domain for fast search
  const hostCandidate = extractHostCandidate(query);
  if (!hostCandidate || hostCandidate.length < 3) {
    throw new HTTPException(400, { message: "Fast search requires a valid domain name" });
  }

  const filters = normalizeAttributeFilters(payload?.attributes ?? payload?.filter);
  const indexMap = await fetchIndexMap("geosite", env);
  const totalAvailable = Object.keys(indexMap).length;
  const requestedNames: string[] = Array.isArray(payload?.names)
    ? payload.names.map((n: unknown) => String(n).trim()).filter((n: string) => n.length > 0)
    : [];
  const scopedNames = requestedNames.length
    ? requestedNames.filter((name) => indexMap[name] !== undefined)
    : Object.keys(indexMap);
  if (scopedNames.length === 0) {
    throw new HTTPException(400, { message: "No valid geosite names in scope" });
  }
  const limit = clamp(Number(payload?.limit ?? 50), 5, 200);

  // For fast search, prioritize lists that might contain the domain
  const domainParts = hostCandidate.toLowerCase().split(".");
  const prioritized = scopedNames.filter((name) => {
    const lower = name.toLowerCase();
    return domainParts.some((part) => part.length > 2 && lower.includes(part));
  });

  const maxLists = clamp(Number(payload?.lists ?? 400), 50, 1000); // Smaller default for fast search
  const dedupedNames = Array.from(new Map([...prioritized, ...scopedNames].map((n) => [n, n])).values());
  const namesForSearch = dedupedNames.slice(0, Math.min(maxLists, dedupedNames.length));

  const startTime = Date.now();
  const { matches, scanned, searchMode } = await searchGeositeRulesFast(
    query,
    filters,
    namesForSearch,
    limit,
    env,
    indexMap,
    namesForSearch.length
  );
  const searchTime = Date.now() - startTime;

  return c.json({
    query,
    filters,
    limit,
    scope: {
      requested: requestedNames,
      used: namesForSearch.length,
      total: totalAvailable,
      scanned,
      prioritized,
    },
    matches,
    searchMode,
    performance: {
      searchTimeMs: searchTime,
      avgTimePerList: namesForSearch.length > 0 ? Math.round(searchTime / namesForSearch.length * 100) / 100 : 0,
    },
  });
});

app.post("/api/search/geoip", async (c) => {
  const env = ((c as any).env || {}) as EnvBindings;
  let payload: any;
  try {
    payload = await c.req.json();
  } catch (error) {
    throw new HTTPException(400, { message: "Invalid JSON payload" });
  }
  const query = String(payload?.query ?? "").trim();
  if (!query) {
    throw new HTTPException(400, { message: "Missing query" });
  }
  // Allow only exact IP or exact CIDR for GeoIP search
  const parsedIp = parseIPAddress(query);
  const isCidrQuery = query.includes("/");
  if (!parsedIp && !isCidrQuery) {
    throw new HTTPException(400, { message: "GeoIP search requires an exact IP or CIDR" });
  }
  // IP version selection is not required; version is inferred from query
  // Read direct from D1 (no KV cache for geoip)
  const listsParam = clamp(Number(payload?.lists ?? 800), 100, 2000);
  const limitParam = clamp(Number(payload?.limit ?? 200), 5, 200); // default widened to 200
  const namesParam: string[] = Array.isArray(payload?.names)
    ? payload.names.map((n: unknown) => String(n).trim()).filter((n: string) => n.length > 0)
    : [];

  const indexMap = await fetchIndexMap("geoip", env);
  const totalAvailable = Object.keys(indexMap).length;
  const requestedNames: string[] = namesParam;
  const scopedNames = requestedNames.length
    ? requestedNames.filter((name) => indexMap[name] !== undefined)
    : Object.keys(indexMap);
  if (scopedNames.length === 0) {
    throw new HTTPException(400, { message: "No valid geoip names in scope" });
  }
  const limit = limitParam;
  // Prioritization is not necessary for exact IP, keep scope order
  const prioritized: string[] = [];
  const maxLists = listsParam;
  const dedupedNames = Array.from(new Map([...prioritized, ...scopedNames].map((n) => [n, n])).values());
  const namesForSearch = dedupedNames.slice(0, Math.min(maxLists, dedupedNames.length));
  const startTime = Date.now();
  const { matches, scanned, mode } = await searchGeoipLists(
    query,
    namesForSearch,
    limit,
    env,
    indexMap,
    namesForSearch.length
  );
  const searchTime = Date.now() - startTime;
  const responseBody = {
    query,
    limit,
    mode,
    scope: {
      requested: requestedNames,
      used: namesForSearch.length,
      total: totalAvailable,
      scanned,
      prioritized,
    },
    matches,
    performance: {
      searchTimeMs: searchTime,
      avgTimePerList: namesForSearch.length > 0 ? Math.round((searchTime / namesForSearch.length) * 100) / 100 : 0,
    },
    generatedAt: Date.now(),
    softTtlSec: SEARCH_SOFT_TTL_SECONDS,
  };
  c.header("Cache-Control", "no-store");
  return c.json(responseBody);
});

app.get("/", (c) => {
  return c.text("Surge Geosite API");
});

app.get("/healthz", (c) => {
  return c.json({ status: "ok" });
});

// SRS (GeoIP) distribution via R2
app.get("/srs-geoip/:name_with_filter", async (c) => {
  let raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  if (!raw.toLowerCase().endsWith(".srs")) {
    throw new HTTPException(404, { message: "Not found" });
  }
  raw = raw.slice(0, -4);
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null; // v4/v6

  const bucket = (c as any).env?.SRS_BUCKET as R2Bucket | undefined;
  if (!bucket) {
    throw new HTTPException(500, { message: "SRS bucket not configured" });
  }
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  let found: R2ObjectBody | null = null;
  let pickedKey = "";
  for (const n of candidates) {
    const key = getGeoipSrsKey(n, filter);
    const obj = await bucket.get(key);
    if (obj) {
      found = obj;
      pickedKey = key;
      break;
    }
  }
  const obj = found;
  if (!obj) {
    throw new HTTPException(404, { message: "SRS not found" });
  }
  const headers = new Headers();
  headers.set("content-type", "application/octet-stream");
  const suggested = pickedKey.split("/").pop() || pickedKey;
  headers.set("content-disposition", `inline; filename="${encodeURIComponent(suggested)}"`);
  if (obj.etag) headers.set("etag", obj.etag);
  return new Response(obj.body, { headers });
});

// MRS (GeoIP) distribution via R2
app.get("/mihomo/geoip/:name_with_filter", async (c) => {
  let raw = c.req.param("name_with_filter").trim();
  if (!raw || raw.length === 0) {
    throw new HTTPException(400, { message: "Invalid name parameter" });
  }
  // Require ".mrs" suffix in URL, e.g. /mrs-geoip/CN.mrs or /mrs-geoip/CN@v4.mrs
  if (!raw.toLowerCase().endsWith(".mrs")) {
    throw new HTTPException(404, { message: "Not found" });
  }
  raw = raw.slice(0, -4);
  const [rawName, rawFilter] = raw.includes("@") ? raw.split("@", 2) : [raw, null];
  const name = rawName;
  const filter = rawFilter ? rawFilter.toLowerCase() : null; // v4/v6

  const bucket = (c as any).env?.SRS_BUCKET as R2Bucket | undefined;
  if (!bucket) {
    throw new HTTPException(500, { message: "MRS bucket not configured" });
  }
  const candidates = Array.from(new Set([name, name.toUpperCase(), name.toLowerCase()]));
  let found: R2ObjectBody | null = null;
  let pickedKey = "";
  for (const n of candidates) {
    const key = getGeoipMrsKey(n, filter);
    const obj = await bucket.get(key);
    if (obj) {
      found = obj;
      pickedKey = key;
      break;
    }
  }

  const obj = found;
  if (!obj) {
    throw new HTTPException(404, { message: "MRS not found" });
  }

  const headers = new Headers();
  headers.set("content-type", "application/octet-stream");
  const suggested = pickedKey.split("/").pop() || pickedKey;
  headers.set("content-disposition", `inline; filename="${encodeURIComponent(suggested)}"`);
  if (obj.etag) headers.set("etag", obj.etag);
  return new Response(obj.body, { headers });
});

app.get("/github", (c) => {
  return c.redirect("https://github.com/jirong0214/Surge-Geosite-Enhance");
});

app.get("/misc/:category/:name", async (c) => {
  const category = c.req.param("category").toLowerCase();
  const name = c.req.param("name").toLowerCase();
  const githubRaw = await fetch(
    `https://raw.githubusercontent.com/Sleepstars/Surge-Geosite-Enhance/refs/heads/main/misc/${category}/${name}.list`
  )
    .then((res) => {
      if (res.ok) {
        return res.text();
      }
      throw new HTTPException(500, {
        message: `Failed to fetch content from GitHub: ${res.status} ${res.statusText}`,
      });
    })
    .catch((err) => {
      throw new HTTPException(500, {
        message: `Failed to fetch content from GitHub: ${err.message}`,
      });
    });
  return c.text(githubRaw);
});

export default app;
